### ISSUE TITLE
Tasks and Defs

### ISSUE THREAD

**Issue by liqMix** [kettek/ebijam22#2]
# Tasks and Defs

* graphics
  * [x] cell based
  * [x] oblique
  * [x] 16x16 cells, larger sprites allowed (rendered from center origin)
* physics
  * [ ] collision
    * [ ] collision blockers (walls & turrets)
  * [ ] sliding
    * [ ] collision with wall at angle preserve momentum
  * [x] attract / repel
    * [x] overlapping magnetic fields, use net vector
    * [x] applies to projecticles
    * [ ] produced by projecticles?
    * [x] produced by enemies
* [x] pathfinding
  * [x] generation on map update
  * [x] calculating ideal steps on entity pathing start

* datatypes
  * [x] base entity
    * [ ] turrets
    * [ ] enemies
    * [x] actor
    * [x] projecticles
  * [x] maps
    * [x] cells
    * [x] entities

* input
  * [x] keys
  * [x] mouse

* resources
  * [x] maps
    * [x] map parser
    * [x] plain text
    * [x] cell
  * [ ] sprites
    * [x] png
  * [ ] bgm
    * [x] ogg format
    * [ ] menu
    * [ ] game
    * [ ] win
    * [ ] loss
  * [ ] sfx
    * [x] ogg format
    * [x] turret place
    * [ ] projecticle fire
    * [ ] enemy death?
    * [ ] enemy spawn?
    * [ ] player death

* [x] states
  * [ ] menu
  * [ ] game
  * [ ] victory/loss

**Comment by kettek** [comment]
Closing this in favor of the new and improved task list #4.
